### ISSUE TITLE
`setOption` should not be called during main process.

### ISSUE THREAD

**Issue by Moxie1776** [ecomfe/vue-echarts#549]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型
`setOption` should not be called during main process. This just started happening after I updated 

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
The same code I was using last week is now giving this error. I copied https://codesandbox.io/s/vue-echarts-toolboxreset-bug-sx231 and the only changes to get this error is listed below.

`<v-chart autoresize :option="chartOptions" />`
 was changed to 
`<v-chart ref="objChart" autoresize :option="chartOptions" @dataZoom=eventZoomData />`
also added to methods so the event has a function to call
`eventZoomData(data){
      console.log(data)
    }`

### Vue version / Vue 版本

- [ ] Vue 3
- [X] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [X] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-beta.5

## Reproduction link / 复现链接
https://codesandbox.io/s/ref-setoption-bug-k329z?file=/pages/index.vue:3629-3679

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your CodeSandbox demo below: ([Vue 3 template](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 template](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue))**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 CodeSandbox 上 demo 的链接：（[Vue 3 模板](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 模板](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue)）**

**Comment by helmut-jacob** [comment]
I'm seeing the same issue with 6.0.0-rc.5, downgrading to 6.0.0-rc.4 fixed it.

Hence, I guess something slipped in between rc4 and rc5.

**Comment by Justineo** [comment]
@helmut-jacob It's actually a different error but may share the same root cause (can't confirm yet).

**Comment by ntnyq** [comment]
downgrade `echarts` to `5.1.0` solved my issue

**Comment by DestinyHunter** [comment]
6.0.0-rc.5 encountered the same problem

**Comment by Justineo** [comment]
It should be fixed in `echarts@5.1.2`, which will be release in a week or two.

**Comment by xmatthias** [comment]
@Justineo i still see this happening with vue-echarts 6.0.0-rc.6 - and echarts 5.1.2

My component is based on input data - so i need to use a getter to compile the Options.
Passing that directly to the Api does raise the same exception as mentioned above 

In my case, i'm only using a very simple chart component.

``` vue
<template>
  <v-chart v-if="dailyStats.data" :option="dailyChartOptions" :theme="getChartTheme" autoresize />
</template>
```
Once it's initialized however - i get
```
 Error: `setOption` should not be called during main process.).
```

As it's part of the getter - i assume it'll run "immediately" (the v-if at the top is really not relevant, as the parent does the same check).

**Comment by pecopeco** [comment]
新版本还是有问题
