### ISSUE TITLE
Event listener not working in Vue 2.7

### ISSUE THREAD

**Issue by kingyue737** [ecomfe/vue-echarts#636]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
echarts 5.3.3
vue 2.7.3
vue-echarts 6.2.2
```

### Details

Should print log in console when hovering on chart, but nothing happens.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kdw9ez

**Comment by youthug** [comment]
loading doesn't work either

**Comment by youthug** [comment]
```vue
<template>
  <v-chart ref="chart" />
</template>

<script lang="ts" setup>
  import { onBeforeUnmount, onMounted, ref } from 'vue'

  const chart = ref(null)

  const handleClick = () => {
    // do something
  }

  onMounted(() => {
    chart?.chart?.on('click', handleClick)
  })

  onBeforeUnmount(() => {
    chart?.chart?.off('click', handleClick)
  })

</script>
```

This works for me

**Comment by Justineo** [comment]
`v-on` should work now by upgrading to `vue-echarts@6.2.3`.

**Comment by youthug** [comment]
> `v-on` should work now by upgrading to `vue-echarts@6.2.3`.

`v-on` worked! but `loading` seems still not working properly

**Comment by Justineo** [comment]
@youthug Please open a new issue with proper reproduction. Thank you!
